#!/usr/bin/python

# toolbar.py

import wx

class MyFrame(wx.Frame):
    def __init__(self, parent, id, title):
        wx.Frame.__init__(self, parent, id, title, wx.DefaultPosition, wx.Size(350, 250))

        vbox = wx.BoxSizer(wx.VERTICAL)
        panel0 = wx.Panel(self,-1)
        panel0.SetBackgroundColour("YELLOW")
        vbox.Add(panel0,1,wx.EXPAND | wx.ALL)
                           
        hbox = wx.BoxSizer(wx.HORIZONTAL)
        panel1 = wx.Panel(self,-1)
        panel1.SetBackgroundColour("RED")
        panel2 = wx.Panel(self,-1)
        panel2.SetBackgroundColour("BLUE")

        hbox.Add(panel1,3,wx.EXPAND |wx.ALL)
        hbox.Add(panel2,1,wx.EXPAND |wx.ALL)

        vbox.Add(hbox,9,wx.EXPAND | wx.ALL)
        
        self.SetSizer(vbox)
        self.Centre()

class MyApp(wx.App):
    def OnInit(self):
        frame = MyFrame(None, -1, 'MyFrame')
        frame.Show(True)
        return True

app = MyApp(0)
app.MainLoop()
