#!/usr/bin/python

# toolbar.py

from visual import *
import wx

class MyWindow(window):
    def __init__(self, parent, id, title):
        window.__init__(self, parent, id, title, wx.DefaultPosition, wx.Size(350, 250))

        # vbox = wx.BoxSizer(wx.VERTICAL)
        # panel0 = wx.Panel(self,-1)
        self.win.panel.SetBackgroundColour("YELLOW")
        vbox.Add(self.win.panel,1,wx.EXPAND | wx.ALL)
                           
        hbox = wx.BoxSizer(wx.HORIZONTAL)
        panel1 = wx.Panel(self,-1)
        panel1.SetBackgroundColour("RED")
        panel2 = wx.Panel(self,-1)
        panel2.SetBackgroundColour("BLUE")

        hbox.Add(panel1,3,wx.EXPAND |wx.ALL)
        hbox.Add(panel2,1,wx.EXPAND |wx.ALL)

        vbox.Add(hbox,9,wx.EXPAND | wx.ALL)
        
        self.SetSizer(vbox)
        self.Centre()

class MyApp(wx.App):
    def OnInit(self):
        window = MyWindow(None, -1, 'Mywindow')
        window.Show(True)
        return True

app = MyApp(0)
app.MainLoop()
